<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <AssemblyName>UStracker.Updater</AssemblyName>
    <RootNamespace>UStracker.Updater</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Shared\RootPaths.cs" Link="Shared\RootPaths.cs" />
  </ItemGroup>
</Project>
