import { formatBRL, formatDateBR } from '../ui/formatters.js';
import { renderEntityAutocomplete } from '../ui/entity-autocomplete.js';
import { codeTag, vehicleCells, vehicleRef } from '../ui/logical-codes.js';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const options=(items,value,label,blank='')=>`${blank?`<option value="">${blank}</option>`:''}${(items||[]).map(x=>`<option value="${esc(x[value])}">${esc(x[label]??x[value])}</option>`).join('')}`;
export function coverageRemaining(endAt,now=new Date()){
  const end=new Date(/T/.test(endAt)?endAt:endAt+'T00:00:00'); const ms=end-now;
  if(ms<=0)return 'Expirado'; const days=Math.ceil(ms/86400000); return `${days} dia${days===1?'':'s'}`;
}
function subRows(items){return items.map(x=>`<tr><td>${codeTag(x.code)||'—'}</td><td>${esc(x.client_name)}</td><td>${esc((x.plans||[]).map(p=>p.name||p.code).join(', ')||'—')}</td><td>${vehicleCells(x.vehicles||[])}</td><td>${formatBRL(x.total_cents)}</td><td>${esc(x.lifecycle_status)}</td><td><button type="button" class="ui-btn ui-btn-subtle" data-buy-client="${esc(x.client_id)}" data-buy-client-name="${esc(x.client_name)}">Compra Direta</button></td></tr>`).join('')||'<tr><td colspan="7" class="muted">Nenhuma assinatura.</td></tr>'}
function saleRows(items){return items.map(x=>`<tr><td>${codeTag(x.code)||'—'}</td><td>${esc(x.client_name)}</td><td>${formatDateBR(x.sold_on)}</td><td>${esc(x.status)}</td><td>${formatBRL(x.total_cents)}</td></tr>`).join('')||'<tr><td colspan="5" class="muted">Nenhuma compra.</td></tr>'}
function coverageRows(items){return items.map(x=>`<tr><td>${esc(x.client_name)} ${codeTag(x.subscription_code)}</td><td>${formatDateBR(x.start_on)}</td><td>${formatDateBR(x.end_on)}</td><td>${x.cycles}</td><td>${formatBRL(x.applied_value_cents)}</td><td>${esc(coverageRemaining(x.end_on))}</td></tr>`).join('')||'<tr><td colspan="6" class="muted">Nenhuma cobertura.</td></tr>'}
function creditRows(items){return items.map(x=>`<tr><td>${esc(x.client_name||'—')} ${codeTag(x.client_code)}</td><td>${formatBRL(x.amount_cents)}</td><td>${formatBRL(x.balance_cents)}</td><td>${esc(x.status)}</td></tr>`).join('')||'<tr><td colspan="4" class="muted">Nenhum crédito.</td></tr>'}
export function renderCommercialPage(data={},active='subscriptions'){
 const avulsa=data.catalog_avulsa||[], vehicles=data.vehicles||[], subs=data.subscriptions||[], payments=data.payments||[];
 return `<h2>Comercial</h2><div class="tabs commercial-tabs"><button data-commercial-tab="subscriptions" class="${active==='subscriptions'?'active':''}">Assinaturas</button><button data-commercial-tab="purchases" class="${active==='purchases'?'active':''}">Compras Diretas</button><button data-commercial-tab="credits" class="${active==='credits'?'active':''}">Créditos/Tempo Ativo</button></div>
 <section data-commercial-panel="subscriptions" ${active==='subscriptions'?'':'hidden'}><div class="actions"><button type="button" class="ui-btn ui-btn-primary" data-new-subscription>Nova Assinatura</button></div><div class="panel"><table class="compact-table"><thead><tr><th>Código</th><th>Cliente</th><th>Plano</th><th>Veículo(s)</th><th>Valor Total</th><th>Status</th><th>Ação</th></tr></thead><tbody>${subRows(subs)}</tbody></table></div></section>
 <section data-commercial-panel="purchases" ${active==='purchases'?'':'hidden'}><div class="panel"><h3>Nova Compra Direta</h3><form id="commercialPurchaseForm"><div class="row">${renderEntityAutocomplete({name:'client_id',label:'Cliente',required:true,selected:data.purchase_client||null})}<div class="field"><label>Produto Avulso</label><select name="catalog_id">${options(avulsa,'id','name')}</select></div><div class="field"><label>Veículo</label><select name="vehicle_id" disabled><option value="">— selecione o cliente —</option>${vehicles.map(row=>`<option value="${esc(row.id)}" data-client="${esc(row.client_id)}" hidden>${esc(vehicleRef(row))}</option>`).join('')}</select></div><div class="field"><label>Quantidade</label><input type="number" min="1" name="quantity" value="1"></div><div class="field"><label>Data contratação</label><input type="date" name="sold_on"></div></div><div class="actions"><button>Registrar compra</button></div></form></div><div class="panel"><table class="compact-table"><thead><tr><th>Código</th><th>Cliente</th><th>Data</th><th>Status</th><th>Total</th></tr></thead><tbody>${saleRows(data.direct_sales||[])}</tbody></table></div></section>
 <section data-commercial-panel="credits" ${active==='credits'?'':'hidden'}><div class="panel"><h3>Registrar Tempo Ativo</h3><form id="coverageForm"><div class="row"><div class="field"><label>Assinatura</label><select name="subscription_id">${options(subs,'id','code')}</select></div><div class="field"><label>Pagamento</label><select name="origin_payment_id">${options(payments,'id','code')}</select></div><div class="field"><label>Ciclos</label><input type="number" min="1" name="cycles" value="1"></div><div class="field"><label>Início</label><input type="date" name="start_on"></div><div class="field"><label>Valor aplicado</label><input type="text" inputmode="decimal" name="value" value="R$ 0,00"></div></div><div class="actions"><button>Registrar cobertura</button></div></form></div><div class="panel"><h3>Tempo Ativo</h3><table class="compact-table"><thead><tr><th>Cliente</th><th>Início</th><th>Fim</th><th>Ciclos</th><th>Valor aplicado</th><th>Restante</th></tr></thead><tbody>${coverageRows(data.coverage_periods||[])}</tbody></table></div><div class="panel"><h3>Créditos monetários</h3><p class="muted">Saldo financeiro permanece separado do tempo de serviço pré-pago.</p><table class="compact-table"><thead><tr><th>Cliente</th><th>Crédito</th><th>Saldo</th><th>Status</th></tr></thead><tbody>${creditRows(data.credits||[])}</tbody></table></div></section>`;
}
