import { formatBRL } from '../ui/formatters.js';
import { codeTag } from '../ui/logical-codes.js';
import { renderVehicleBreakdown } from '../ui/vehicle-breakdown.js';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const monthLabel=competence=>{const [y,m]=String(competence||'').split('-');const names=['jan','fev','mar','abr','mai','jun','jul','ago','set','out','nov','dez'];return m?`${names[Number(m)-1]||m}/${y}`:''};
export function renderOverviewPage(data={},query='',selectedYear=''){
 const rows=(data.client_activity||[]).map(r=>`<tr><td>${esc(r.client_name)} ${codeTag(r.client_code)}</td><td>${r.vehicles_count}</td><td>${r.active_subscriptions}</td><td>${r.purchases_count}</td><td class="money">${formatBRL(r.contracted_active_cents||0)}${Number(r.open_purchases_cents||0)?`<span class="forecast-detail">+ ${formatBRL(r.open_purchases_cents)} em compras abertas</span>`:''}</td><td class="money">${formatBRL(r.realized_revenue_cents??r.value_generated_cents??0)}</td><td>${esc(r.status)}</td><td><button type="button" class="ui-btn ui-btn-subtle" data-profile-id="${esc(r.client_id)}">Abrir Ficha</button></td></tr>`).join('')||'<tr><td colspan="8" class="muted">Nenhum cliente encontrado.</td></tr>';
 const period=data.period||{};const years=data.available_years||[];const forecast=data.month_forecast||{};
 const revenue=`<div class="card revenue-split"><div><div class="value">${formatBRL(period.revenue_cents||0)}</div><div class="label">Receita Geral</div><span class="forecast-detail">Realizada até hoje · ${esc(period.label||'Geral')}</span></div><div><div class="value">${formatBRL(forecast.forecast_cents||0)}</div><div class="label">Previsão do Mês ${esc(monthLabel(forecast.competence))}</div><span class="forecast-tag">Não realizada · fora do Resultado</span><span class="forecast-detail">Recebido no mês: ${formatBRL(forecast.received_in_month_cents||0)}</span></div></div>`;
 return `<h2>Visão Geral</h2><div class="panel r2-operational"><div class="indicators-head"><h3>Indicadores ${esc(period.label||'Gerais')}</h3><form id="overviewPeriod"><div class="field"><label>Período</label><select name="year"><option value="">Geral</option>${years.map(year=>`<option value="${year}" ${String(selectedYear)===String(year)?'selected':''}>${year}</option>`).join('')}</select></div></form></div><div class="cards overview-kpis">${revenue}<div class="card"><div class="value">${formatBRL(period.expenses_cents||0)}</div><div class="label">Despesas Gerais</div></div><div class="card ${Number(period.result_cents||0)>=0?'result-positive':'result-negative'}"><div class="value">${formatBRL(period.result_cents||0)}</div><div class="label">Resultado</div><span class="forecast-detail">Receita Geral − Despesas Gerais</span></div><div class="card"><div class="value">${esc(data.active_clients??0)}</div><div class="label">Clientes Ativos</div></div><div class="card"><div class="value">${esc(data.active_subscriptions??0)}</div><div class="label">Assinaturas Ativas</div></div></div>
 <div class="overview-vehicles">${renderVehicleBreakdown(data.vehicle_breakdown||{total:data.active_vehicles||0,categories:[]})}</div></div>
 <div class="panel"><form id="overviewSearch" class="overview-search"><div class="field"><label>Pesquisar clientes</label><input name="q" value="${esc(query)}" placeholder="Nome do cliente"></div><div class="actions"><button>Pesquisar</button><button type="button" class="secondary" id="overviewClear">Limpar</button></div></form></div>
 <div class="panel"><h3>Clientes</h3><div class="overview-table-wrap"><table id="overviewClients" class="compact-table overview-table"><thead><tr><th>Cliente</th><th>Veículos</th><th>Assinaturas</th><th>Compras</th><th>Valor contratado ativo</th><th>Receita realizada</th><th>Status</th><th>Ação</th></tr></thead><tbody>${rows}</tbody></table></div></div>`;
}
