import { formatBRL } from '../ui/formatters.js';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
export function renderOverviewPage(data={},query='',selectedYear=''){
 const rows=(data.client_activity||[]).map(r=>`<tr><td>${esc(r.client_name)}</td><td>${r.vehicles_count}</td><td>${r.active_subscriptions}</td><td>${r.purchases_count}</td><td>${formatBRL(r.value_generated_cents)}</td><td>${esc(r.status)}</td><td><button type="button" class="ui-btn ui-btn-subtle" data-profile-id="${esc(r.client_id)}">Abrir Ficha</button></td></tr>`).join('')||'<tr><td colspan="7" class="muted">Nenhum cliente encontrado.</td></tr>';
 const period=data.period||{};const years=data.available_years||[];
 return `<h2>Visão Geral</h2><div class="panel overview-period"><form id="overviewPeriod"><div class="field"><label>Período dos indicadores</label><select name="year"><option value="">Geral</option>${years.map(year=>`<option value="${year}" ${String(selectedYear)===String(year)?'selected':''}>${year}</option>`).join('')}</select></div></form></div><div class="panel r2-operational"><h3>Indicadores ${esc(period.label||'Gerais')}</h3><div class="cards overview-kpis"><div class="card"><div class="value">${formatBRL(period.revenue_cents||0)}</div><div class="label">Receita Geral</div></div><div class="card"><div class="value">${formatBRL(period.expenses_cents||0)}</div><div class="label">Despesas Gerais</div></div><div class="card ${Number(period.result_cents||0)>=0?'result-positive':'result-negative'}"><div class="value">${formatBRL(period.result_cents||0)}</div><div class="label">Resultado</div></div><div class="card"><div class="value">${esc(data.active_clients??0)}</div><div class="label">Clientes Ativos</div></div><div class="card"><div class="value">${esc(data.active_vehicles??0)}</div><div class="label">Veículos</div></div><div class="card"><div class="value">${esc(data.active_subscriptions??0)}</div><div class="label">Assinaturas Ativas</div></div></div></div>
 <div class="panel"><form id="overviewSearch" class="overview-search"><div class="field"><label>Pesquisar clientes</label><input name="q" value="${esc(query)}" placeholder="Nome do cliente"></div><div class="actions"><button>Pesquisar</button><button type="button" class="secondary" id="overviewClear">Limpar</button></div></form></div>
 <div class="panel"><h3>Clientes</h3><div class="overview-table-wrap"><table id="overviewClients" class="compact-table overview-table"><thead><tr><th>Cliente</th><th>Veículos</th><th>Assinaturas</th><th>Compras</th><th>Valor Gerado</th><th>Status</th><th>Ação</th></tr></thead><tbody>${rows}</tbody></table></div></div>`;
}
