import { formatBRL, formatDateBR } from '../ui/formatters.js';
import { renderEntityAutocomplete } from '../ui/entity-autocomplete.js';
import { codeTag } from '../ui/logical-codes.js';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const options=(items,value,label,blank='')=>`${blank?`<option value="">${blank}</option>`:''}${(items||[]).map(x=>`<option value="${esc(x[value])}">${esc(x[label]??x[value])}</option>`).join('')}`;
const paymentRows=items=>items.map(x=>`<tr><td>${codeTag(x.code)||'—'}</td><td>${formatDateBR(x.paid_on)}</td><td>${formatBRL(x.amount_cents)}</td><td>${esc(x.method||'—')}</td><td>${x.reversed_at?'Estornado':'Ativo'}</td></tr>`).join('')||'<tr><td colspan="5" class="muted">Nenhum recebimento.</td></tr>';
const expenseRows=items=>items.map(x=>`<tr><td>${esc(x.description)}</td><td>${esc(x.competence)}</td><td>${formatBRL(x.expected_amount_cents)}</td><td>${esc(x.status)}</td></tr>`).join('')||'<tr><td colspan="4" class="muted">Nenhuma despesa.</td></tr>';
const fiscalRows=items=>items.map(x=>`<tr><td>${esc(x.description)}</td><td>${esc(x.competence)}</td><td>${x.amount_cents==null?'—':formatBRL(x.amount_cents)}</td><td>${esc(x.status)}</td><td>${x.expense_id?'Vinculada':'—'}</td></tr>`).join('')||'<tr><td colspan="5" class="muted">Nenhuma obrigação fiscal.</td></tr>';
export function renderFinancePage(data={},active='payments'){
 const charges=data.charges||[];
 return `<h2>Financeiro</h2><div class="tabs finance-tabs"><button data-finance-tab="payments" class="${active==='payments'?'active':''}">Recebimentos</button><button data-finance-tab="expenses" class="${active==='expenses'?'active':''}">Despesas</button><button data-finance-tab="fiscal" class="${active==='fiscal'?'active':''}">Fiscal</button></div>
 <section data-finance-panel="payments" ${active==='payments'?'':'hidden'}><div class="panel"><h3>Novo recebimento</h3><form id="financePaymentForm"><div class="row">${renderEntityAutocomplete({name:'client_id',label:'Cliente',required:true})}<div class="field"><label>Valor</label><input type="text" inputmode="decimal" name="amount" value="R$ 0,00"></div><div class="field"><label>Data</label><input type="date" name="paid_on"></div><div class="field"><label>Método</label><input name="method"></div><div class="field"><label>Cobrança</label><select name="charge_id" disabled><option value="">— selecione o cliente —</option>${charges.map(row=>`<option value="${esc(row.id)}" data-client="${esc(row.client_id)}" hidden>${esc(row.code||'Cobrança')} · ${esc(formatBRL(Number(row.amount_cents||0)+Number(row.adjustment_cents||0)))}</option>`).join('')}</select></div><div class="field"><label>Valor alocado</label><input type="text" inputmode="decimal" name="allocation_amount" value="R$ 0,00"></div></div><label><input type="checkbox" name="create_credit" value="true"> Transformar sobra em crédito</label><div class="actions"><button>Registrar recebimento</button></div></form></div><div class="panel"><table class="compact-table"><thead><tr><th>Código</th><th>Data</th><th>Valor</th><th>Método</th><th>Situação</th></tr></thead><tbody>${paymentRows(data.payments||[])}</tbody></table></div></section>
 <section data-finance-panel="expenses" ${active==='expenses'?'':'hidden'}><div class="panel"><h3>Nova despesa</h3><form id="financeExpenseForm"><div class="row"><div class="field"><label>Categoria</label><input name="category" required></div><div class="field"><label>Descrição</label><input name="description" required></div><div class="field"><label>Competência</label><input type="month" name="competence" required></div><div class="field"><label>Valor previsto</label><input type="text" inputmode="decimal" name="expected_amount" value="R$ 0,00" required></div><div class="field"><label>Vencimento</label><input type="date" name="due_on"></div><div class="field"><label>Fornecedor</label><input name="supplier"></div></div><div class="actions"><button>Salvar despesa</button></div></form></div><div class="panel"><table class="compact-table"><thead><tr><th>Descrição</th><th>Competência</th><th>Valor</th><th>Status</th></tr></thead><tbody>${expenseRows(data.expenses||[])}</tbody></table></div></section>
 <section data-finance-panel="fiscal" ${active==='fiscal'?'':'hidden'}><div class="notice">Controle administrativo. Não emite documento fiscal oficial.</div><div class="panel"><h3>Nova obrigação fiscal</h3><form id="financeFiscalForm"><div class="row"><div class="field"><label>Competência</label><input type="month" name="competence" required></div><div class="field"><label>Descrição</label><input name="description" required></div><div class="field"><label>Valor</label><input type="text" inputmode="decimal" name="amount" value=""></div><div class="field"><label>Vencimento</label><input type="date" name="due_on"></div><div class="field"><label>Referência externa</label><input name="external_ref"></div></div><div class="actions"><button>Salvar obrigação</button></div></form></div><div class="panel"><table class="compact-table"><thead><tr><th>Descrição</th><th>Competência</th><th>Valor</th><th>Status</th><th>Despesa</th></tr></thead><tbody>${fiscalRows(data.fiscal||[])}</tbody></table></div></section>`;
}
