import { formatBRL, formatDateBR } from '../ui/formatters.js';
import { renderEntityAutocomplete } from '../ui/entity-autocomplete.js';
import { codeTag } from '../ui/logical-codes.js';
import { localToday } from '../ui/payment-dialog.js';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
// AJ-13 — fixed categories for UStracker's own costs.
export const EXPENSE_CATEGORIES=['Insumos','Equipamentos','Mensalidades e serviços','Pessoal','Impostos e taxas','Marketing','Infraestrutura','Outros'];
export const EXPENSE_REPEAT=[['MONTHLY','Mensal'],['ANNUAL','Anual'],['ONCE','Única']];
const STATUS={OPEN:'A pagar',PARTIAL:'Parcial',PAID:'Paga'};
const paymentRows=items=>items.map(x=>`<tr class="${x.reversed_at?'is-muted':''}"><td>${codeTag(x.code)||'—'}</td><td>${esc(x.client_name||'—')}</td><td>${formatDateBR(x.paid_on)}</td><td class="num">${formatBRL(x.amount_cents)}</td><td>${esc(x.method||'—')}</td><td>${x.reversed_at?'<span class="badge badge-muted">Estornado</span>':'<span class="badge badge-ok">Recebido</span>'}</td><td>${x.reversed_at?'':`<button type="button" class="ui-btn ui-btn-subtle ui-btn-sm" data-reverse-payment="${esc(x.id)}">Estornar</button>`}</td></tr>`).join('')||'<tr><td colspan="7" class="muted">Nenhum recebimento.</td></tr>';
function expenseActions(x){
  const out=[];
  if(x.status!=='PAID')out.push(`<button type="button" class="ui-btn ui-btn-primary ui-btn-sm" data-expense-pay="${esc(x.id)}">Pagar</button>`);
  if(x.is_template&&Number(x.repeat_active))out.push(`<button type="button" class="ui-btn ui-btn-subtle ui-btn-sm" data-expense-stop="${esc(x.id)}">Parar repetição</button>`);
  if((x.repeat||'ONCE')==='ONCE'&&!x.converted_sale_id)out.push(`<button type="button" class="ui-btn ui-btn-subtle ui-btn-sm" data-expense-sell="${esc(x.id)}">Vender ao cliente</button>`);
  if(!Number(x.paid_cents)&&!x.converted_sale_id)out.push(`<button type="button" class="ui-btn ui-btn-danger ui-btn-sm" data-expense-delete="${esc(x.id)}">Excluir</button>`);
  return `<div class="row-actions">${out.join('')}</div>`;
}
const expenseRows=items=>items.map(x=>`<tr><td><span class="cat-chip">${esc(x.category_label||x.category)}</span></td><td>${esc(x.description)}${x.sale_code?` <span class="muted">→ venda</span> ${codeTag(x.sale_code)}`:''}</td><td><span class="badge ${x.repeat==='ONCE'||!x.repeat?'badge-muted':'badge-info'}">${esc(x.repeat_label||'Única')}</span></td><td>${formatDateBR(x.due_on||x.competence)}</td><td class="num">${formatBRL(x.expected_amount_cents)}</td><td><span class="badge ${x.status==='PAID'?'badge-ok':x.status==='PARTIAL'?'badge-warn':'badge-alert'}">${esc(STATUS[x.status]||x.status)}</span></td><td>${expenseActions(x)}</td></tr>`).join('')||'<tr><td colspan="7" class="muted">Nenhuma despesa.</td></tr>';
const fiscalRows=items=>items.map(x=>`<tr><td>${esc(x.description)}</td><td>${esc(x.competence)}</td><td>${x.amount_cents==null?'—':formatBRL(x.amount_cents)}</td><td>${esc(x.status)}</td><td>${x.expense_id?'Vinculada':'—'}</td></tr>`).join('')||'<tr><td colspan="5" class="muted">Nenhuma obrigação fiscal.</td></tr>';
function expenseTotals(items){
  const open=items.filter(x=>x.status!=='PAID').reduce((a,x)=>a+Number(x.open_cents??x.expected_amount_cents??0),0);
  const recurring=items.filter(x=>x.is_template&&Number(x.repeat_active)).length;
  return {open,recurring};
}
export function renderExpenseForm(categories=EXPENSE_CATEGORIES){
  return `<form id="financeExpenseForm" class="quick-form"><div class="row"><div class="field"><label>Categoria</label><select name="category" required>${categories.map(c=>`<option>${esc(c)}</option>`).join('')}</select></div><div class="field field-wide"><label>Descrição</label><input name="description" required placeholder="Ex.: Chip M2M, Rastreador, Plataforma"></div><div class="field"><label>Valor</label><input type="text" inputmode="decimal" data-money-input name="amount" placeholder="R$ 0,00" required></div></div>
  <div class="row"><div class="field"><label>Repetição</label><div class="segmented" role="radiogroup" aria-label="Repetição">${EXPENSE_REPEAT.map(([v,l],i)=>`<label><input type="radio" name="repeat" value="${v}"${i===0?' checked':''}><span>${l}</span></label>`).join('')}</div></div><div class="field"><label>Data</label><input type="date" name="date" value="${esc(localToday())}" required></div><div class="field field-check"><label><input type="checkbox" name="paid" value="true" checked> Já paga</label></div></div>
  <details class="more-options"><summary>Mais opções</summary><div class="row"><div class="field"><label>Fornecedor</label><input name="supplier"></div></div></details>
  <div class="actions"><button class="ui-btn ui-btn-primary">Salvar despesa</button></div></form>`;
}
export function renderFinancePage(data={},active='payments'){
 const charges=data.charges||[]; const expenses=data.expenses||[]; const totals=expenseTotals(expenses);
 return `<h2>Financeiro</h2><div class="tabs finance-tabs"><button data-finance-tab="payments" class="${active==='payments'?'active':''}">Recebimentos</button><button data-finance-tab="expenses" class="${active==='expenses'?'active':''}">Despesas</button><button data-finance-tab="fiscal" class="${active==='fiscal'?'active':''}">Fiscal</button></div>
 <section data-finance-panel="payments" ${active==='payments'?'':'hidden'}><div class="hero-action"><div><h3>Pagamento de assinatura</h3><p class="muted">Escolha o cliente, a assinatura e quantos meses ele está pagando. Atrasados primeiro; os demais ficam adiantados.</p></div><button type="button" class="ui-btn ui-btn-primary ui-btn-lg" data-open-payment>Registrar pagamento</button></div>
 <details class="more-options panel"><summary>Recebimento manual (avançado)</summary><form id="financePaymentForm"><div class="row">${renderEntityAutocomplete({name:'client_id',label:'Cliente',required:true})}<div class="field"><label>Valor</label><input type="text" inputmode="decimal" name="amount" value="R$ 0,00"></div><div class="field"><label>Data</label><input type="date" name="paid_on"></div><div class="field"><label>Método</label><input name="method"></div><div class="field"><label>Cobrança</label><select name="charge_id" disabled><option value="">— selecione o cliente —</option>${charges.map(row=>`<option value="${esc(row.id)}" data-client="${esc(row.client_id)}" hidden>${esc(row.code||'Cobrança')} · ${esc(formatBRL(Number(row.amount_cents||0)+Number(row.adjustment_cents||0)))}</option>`).join('')}</select></div><div class="field"><label>Valor alocado</label><input type="text" inputmode="decimal" name="allocation_amount" value="R$ 0,00"></div></div><label><input type="checkbox" name="create_credit" value="true"> Transformar sobra em crédito</label><div class="actions"><button>Registrar recebimento</button></div></form></details>
 <div class="panel"><table class="compact-table"><thead><tr><th>Código</th><th>Cliente</th><th>Data</th><th class="num">Valor</th><th>Forma</th><th>Situação</th><th>Ação</th></tr></thead><tbody>${paymentRows(data.payments||[])}</tbody></table></div></section>
 <section data-finance-panel="expenses" ${active==='expenses'?'':'hidden'}><div class="kpi-strip"><div><span>A pagar</span><b>${formatBRL(totals.open)}</b></div><div><span>Despesas recorrentes ativas</span><b>${totals.recurring}</b></div><div><span>Pagas (custo realizado)</span><b>${formatBRL(Number(data.realized_expenses_cents||0))}</b></div></div>
 <div class="panel"><h3>Nova despesa</h3><p class="muted">Custos da UStracker: tudo que for pago entra no custo final. Mensal e Anual se repetem sozinhas.</p>${renderExpenseForm(data.expense_categories||EXPENSE_CATEGORIES)}</div><div class="panel"><table class="compact-table"><thead><tr><th>Categoria</th><th>Descrição</th><th>Repetição</th><th>Data</th><th class="num">Valor</th><th>Situação</th><th>Ações</th></tr></thead><tbody>${expenseRows(expenses)}</tbody></table></div></section>
 <section data-finance-panel="fiscal" ${active==='fiscal'?'':'hidden'}><div class="notice">Controle administrativo. Não emite documento fiscal oficial.</div><div class="panel"><h3>Nova obrigação fiscal</h3><form id="financeFiscalForm"><div class="row"><div class="field"><label>Competência</label><input type="month" name="competence" required></div><div class="field"><label>Descrição</label><input name="description" required></div><div class="field"><label>Valor</label><input type="text" inputmode="decimal" name="amount" value=""></div><div class="field"><label>Vencimento</label><input type="date" name="due_on"></div><div class="field"><label>Referência externa</label><input name="external_ref"></div></div><div class="actions"><button>Salvar obrigação</button></div></form></div><div class="panel"><table class="compact-table"><thead><tr><th>Descrição</th><th>Competência</th><th>Valor</th><th>Status</th><th>Despesa</th></tr></thead><tbody>${fiscalRows(data.fiscal||[])}</tbody></table></div></section>`;
}
export function renderSellExpenseForm(expense){
  return `<form id="sellExpenseForm"><p>${esc(expense.description)} · custo ${esc(formatBRL(Number(expense.expected_amount_cents||0)))}</p><div class="row">${renderEntityAutocomplete({name:'client_id',label:'Cliente',required:true})}<div class="field"><label>Preço de venda</label><input type="text" inputmode="decimal" data-money-input name="price" value="${esc(formatBRL(Number(expense.expected_amount_cents||0)))}" required></div></div><p class="muted">Cria uma Compra Direta em aberto para o cliente. O custo continua registrado como despesa.</p><div class="actions"><button class="ui-btn ui-btn-primary">Criar compra direta</button></div></form>`;
}
